# Spring App Info
spring.application.name=task-manager

# Server
server.port=8080

# Datasource (H2)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.org.springframework=DEBUG

# JWT Configuration
jwt.secret=SecretKey1234567890
jwt.expiration=3600000
